In [ ]:
from  pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
from sklearn import preprocessing
import pandas as pd

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
import os
import numpy as np


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
file_path = '/content/drive/My Drive/AIML courseProject/Data.csv'
X_data = pd.read_csv(file_path)
file_path = '/content/drive/My Drive/AIML courseProject/Label.csv'
Y_data = pd.read_csv(file_path)



In [ ]:

typeOfAttacks = {
    "Benign": 0,
    "Analysis": 1,
    "Backdoor": 2,
    "DoS": 3,
    "Exploits": 4,
    "Fuzzers": 5,
    "Generic": 6,
    "Reconnaissance": 7,
    "Shellcode": 8,
    "Worms": 9
}

In [ ]:

X_data.columns

X_data['type'] = Y_data.replace({
    0: "Benign",
    1: "Analysis",
    2: "Backdoor",
    3: "DoS",
    4: "Exploits",
    5: "Fuzzers",
    6: "Generic",
    7: "Reconnaissance",
    8: "Shellcode",
    9: "Worms"
}
)

In [ ]:
X_data['type']

0               Exploits
1         Reconnaissance
2               Exploits
3                    DoS
4                Generic
               ...      
447910            Benign
447911            Benign
447912            Benign
447913            Benign
447914            Benign
Name: type, Length: 447915, dtype: object

In [ ]:
# X=X_data.groupby('type').count()

In [ ]:
intrusion_types = ["Backdoor", "DoS", "Exploits", "Fuzzers", "Reconnaissance", "Shellcode", "Worms"]
non_intrusion_types = ["Benign", "Analysis", "Generic"]


data1 =X[X.index.isin(intrusion_types)]
data2 =X[X.index.isin(non_intrusion_types)]

data11=data1['Flow Duration']
data22=data2['Flow Duration']

display(data11,data22)


type
Backdoor            452
DoS                4467
Exploits          30951
Fuzzers           29613
Reconnaissance    16735
Shellcode          2102
Worms               246
Name: Flow Duration, dtype: int64

type
Analysis       385
Benign      358332
Generic       4632
Name: Flow Duration, dtype: int64

In [ ]:
listOfIntrusionTypes = [2,3,4,5,7,8,9]

In [ ]:
print(X_data.shape)
print(Y_data.shape)

(447915, 76)
(447915, 1)


# **We check for null columns**

In [ ]:
print("DATA")
print(X_data.isnull().sum())
print()
print()
print("Label")
print(Y_data.isnull().sum())

DATA
Flow Duration                 0
Total Fwd Packet              0
Total Bwd packets             0
Total Length of Fwd Packet    0
Total Length of Bwd Packet    0
                             ..
Active Min                    0
Idle Mean                     0
Idle Std                      0
Idle Max                      0
Idle Min                      0
Length: 76, dtype: int64


Label
Label    0
dtype: int64


##As there are no null colums data is already processed we check for feature selection

#**Feature selection**

In [ ]:
# from sklearn.feature_selection import SelectKBest, f_regression


# selector = SelectKBest(score_func=f_regression, k=15)
# X_selected = selector.fit_transform(X_data, Y_data)

# # Get the selected feature names
# selected_features = X_data.columns[selector.get_support()]
# print(selected_features)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Index(['Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Min', 'FIN Flag Count',
       'PSH Flag Count', 'Down/Up Ratio', 'Fwd Segment Size Avg',
       'Fwd Seg Size Min'],
      dtype='object')


## All Features
##  
       'Flow Duration', 'Total Fwd Packet', 'Total Bwd packets',
       'Total Length of Fwd Packet', 'Total Length of Bwd Packet',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWR Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Fwd Segment Size Avg', 'Bwd Segment Size Avg',
       'Fwd Bytes/Bulk Avg', 'Fwd Packet/Bulk Avg', 'Fwd Bulk Rate Avg',
       'Bwd Bytes/Bulk Avg', 'Bwd Packet/Bulk Avg', 'Bwd Bulk Rate Avg',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'FWD Init Win Bytes', 'Bwd Init Win Bytes',
       'Fwd Act Data Pkts', 'Fwd Seg Size Min', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min'

In [ ]:
# X = X_data.drop(columns=[col for col in X_data.columns if col not in selected_features])
X = X_data
X.columns

Index(['Flow Duration', 'Total Fwd Packet', 'Total Bwd packets',
       'Total Length of Fwd Packet', 'Total Length of Bwd Packet',
       'Fwd Packet Length Max', 'Fwd Packet Length Min',
       'Fwd Packet Length Mean', 'Fwd Packet Length Std',
       'Bwd Packet Length Max', 'Bwd Packet Length Min',
       'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags',
       'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Packet Length Min', 'Packet Length Max', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag C

## The values for Flow Bytes/s,Flow Packets/s, Fwd Packets/s are very high so we normalise them

In [ ]:
X['Flow Bytes/s']= (X['Flow Bytes/s'] - X['Flow Bytes/s'].min()) / (X['Flow Bytes/s'].max() - X['Flow Bytes/s'].min())
X['Flow Packets/s']= (X['Flow Packets/s'] - X['Flow Packets/s'].min()) / (X['Flow Packets/s'].max() - X['Flow Packets/s'].min())
X['Fwd Packets/s']= (X['Fwd Packets/s'] - X['Fwd Packets/s'].min()) / (X['Fwd Packets/s'].max() - X['Fwd Packets/s'].min())

In [ ]:
X.describe()

Flow Duration  Total Fwd Packet  Total Bwd packets  \
count   4.479150e+05     447915.000000      447915.000000   
mean    5.983003e+05         22.598428          27.238503   
std     4.878777e+06        127.986936         116.638803   
min     1.000000e+00          1.000000           0.000000   
25%     3.490000e+02          1.000000           2.000000   
50%     5.788000e+03          3.000000           2.000000   
75%     1.792405e+05         17.000000          15.000000   
max     1.199975e+08      20038.000000       11021.000000   

       Total Length of Fwd Packet  Total Length of Bwd Packet  \
count                4.479150e+05                4.479150e+05   
mean                 4.778406e+03                2.170251e+04   
std                  1.518561e+05                1.477431e+05   
min                  0.000000e+00                0.000000e+00   
25%                  0.000000e+00                0.000000e+00   
50%                  9.000000e+01                1.060000e+02   
75%                  4.860000e+02                1.512000e+03   
max                  2.605270e+07                1.421599e+07   

       Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
count          447915.000000          447915.000000           447915.000000   
mean              174.243153              14.918360               71.264324   
std               352.171446              71.570572              184.565303   
min                 0.000000               0.000000                0.000000   
25%                 0.000000               0.000000                0.000000   
50%                45.000000               0.000000                9.346154   
75%               163.000000               0.000000               50.000000   
max              1476.000000            1472.000000             1474.000000   

       Fwd Packet Length Std  Bwd Packet Length Max  ...  Fwd Act Data Pkts  \
count          447915.000000          447915.000000  ...      447915.000000   
mean               64.000867             365.009993  ...           8.628521   
std               156.387353             555.808533  ...         118.663262   
min                 0.000000               0.000000  ...           0.000000   
25%                 0.000000               0.000000  ...           0.000000   
50%                 0.000000              48.000000  ...           1.000000   
75%                29.277002             731.000000  ...          10.000000   
max               848.528137            1460.000000  ...       20032.000000   

       Fwd Seg Size Min   Active Mean    Active Std    Active Max  \
count     447915.000000  4.479150e+05  4.479150e+05  4.479150e+05   
mean          25.926651  1.868487e+04  9.409518e+03  3.126578e+04   
std            9.017636  7.487275e+05  5.231382e+05  1.174788e+06   
min            8.000000  0.000000e+00  0.000000e+00  0.000000e+00   
25%           20.000000  0.000000e+00  0.000000e+00  0.000000e+00   
50%           32.000000  0.000000e+00  0.000000e+00  0.000000e+00   
75%           32.000000  0.000000e+00  0.000000e+00  0.000000e+00   
max           40.000000  1.104063e+08  7.417760e+07  1.104063e+08   

         Active Min     Idle Mean      Idle Std      Idle Max      Idle Min  
count  4.479150e+05  4.479150e+05  4.479150e+05  4.479150e+05  4.479150e+05  
mean   1.252120e+04  9.859284e+04  3.341817e+03  1.026228e+05  9.578854e+04  
std    6.397847e+05  2.222806e+06  2.201782e+05  2.260988e+06  2.207332e+06  
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
50%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
75%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
max    1.104063e+08  1.191926e+08  7.214360e+07  1.191926e+08  1.191926e+08  

[8 rows x 76 columns]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y_data, test_size=0.2, random_state=42)

# Shape of train and test data

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(358332, 76)
(89583, 76)
(358332, 1)
(89583, 1)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split


# Random Forest
model = RandomForestClassifier(n_estimators=400, random_state=42)
model.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=400, random_state=42)

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix





print("----------------------------------------------------------------------")
print("Training Accuracy")
display(model.score(X_train,y_train))
print("----------------------------------------------------------------------")

y_pred = model.predict(X_test)
# ypred=np.argmax(y_pred)


print("----------------------------------------------------------------------")
print("Confusion matrix")
print(confusion_matrix(y_test, y_pred))
print("----------------------------------------------------------------------")

print("----------------------------------------------------------------------")
print("Classification report:")
print(classification_report(y_test, y_pred))
print("----------------------------------------------------------------------")



----------------------------------------------------------------------
Training Accuracy


0.9973878972572922

----------------------------------------------------------------------
----------------------------------------------------------------------
Confusion matrix
[[70488    23     0     8   204   853    15    97    12     1]
 [   10    27     0     4    27     0     0     0     0     0]
 [    3     0    51     0    15    24     0    10     1     0]
 [   29     9     0   295   371   140     9    45    17     1]
 [   98    25     3    74  4942   734    37   319    24     3]
 [  268     2     2    26   371  4868    42   207    63     0]
 [   18     1     0     4    84    84   660    13     3     0]
 [   81     0     1    20   389   543     4  2347     6     1]
 [   15     0     0     7    53   140     2    31   133     0]
 [    2     0     0     0    12    18     1     0     0    13]]
----------------------------------------------------------------------
----------------------------------------------------------------------
Classification report:
              precision    recall  f1-score  

# Applying CNN

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Prepare the data
X = X_data.values
y = Y_data


# Encode labels if they are categorical
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Reshape X for CNN (samples, height, width, channels)
# In this case, we can treat each feature set as a single "image"
X_reshaped = X.reshape((X.shape[0], X.shape[1], 1))  # Shape (samples, 15, 1)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_encoded, test_size=0.2, random_state=42)

# Define the CNN model
model3 = models.Sequential()
model3.add(layers.Conv1D(32, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model3.add(layers.MaxPooling1D(pool_size=2))
model3.add(layers.Conv1D(64, kernel_size=3, activation='relu'))
model3.add(layers.MaxPooling1D(pool_size=2))
# model3.add(layers.Conv1D(128, kernel_size=3, activation='relu'))
# model3.add(layers.MaxPooling1D(pool_size=2))
model3.add(layers.Flatten())
model3.add(layers.Dense(128, activation='relu'))
model3.add(layers.Dense(len(np.unique(y_encoded)), activation='softmax'))

# Compile the model
model3.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model3.summary()

# Train the model
tf_callback = tf.keras.callbacks.TensorBoard(log_dir="logs/lstm",histogram_freq=1)
history = model3.fit(X_train, y_train, epochs=15, batch_size=64, validation_data=(X_test, y_test),callbacks=[tf_callback])

# Evaluate the model
test_loss, test_accuracy = model3.evaluate(X_test, y_test)
print(f'Test accuracy: {test_accuracy:.4f}')


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_2 (Conv1D)                    │ (None, 74, 32)              │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_2 (MaxPooling1D)       │ (None, 37, 32)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_3 (Conv1D)                    │ (None, 35, 64)              │           6,208 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_3 (MaxPooling1D)       │ (None, 17, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 1088)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │         139,392 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 147,018 (574.29 KB)

 Trainable params: 147,018 (574.29 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 29s 5ms/step - accuracy: 0.8101 - loss: 8145.3081 - val_accuracy: 0.8909 - val_loss: 0.3024
Epoch 2/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 35s 4ms/step - accuracy: 0.8963 - loss: 0.4113 - val_accuracy: 0.9044 - val_loss: 0.3199
Epoch 3/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 40s 4ms/step - accuracy: 0.9001 - loss: 0.4190 - val_accuracy: 0.8993 - val_loss: 0.2892
Epoch 4/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 41s 4ms/step - accuracy: 0.9039 - loss: 0.3694 - val_accuracy: 0.9060 - val_loss: 0.2636
Epoch 5/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 41s 4ms/step - accuracy: 0.9053 - loss: 1.0723 - val_accuracy: 0.9069 - val_loss: 0.2551
Epoch 6/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.9076 - loss: 0.5062 - val_accuracy: 0.9116 - val_loss: 0.2465
Epoch 7/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.9115 - loss: 0.2775 - val_accuracy: 0.9114 - val_loss: 0.2480
Epoch 8/15
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.9117 - loss

In [ ]:
# print(test_loss,test_accuracy)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix





print("----------------------------------------------------------------------")
# print("Training Accuracy")
# display(model3.score(X_train,y_train))
# print("----------------------------------------------------------------------")

y_pred = model3.predict(X_test)
ypred= [np.argmax(x) for x in y_pred]


print("----------------------------------------------------------------------")
print("Confusion matrix")
print(confusion_matrix(y_test, ypred))
print("----------------------------------------------------------------------")

print("----------------------------------------------------------------------")
print("Classification report:")
print(classification_report(y_test, ypred))
print("----------------------------------------------------------------------")



----------------------------------------------------------------------
2800/2800 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
----------------------------------------------------------------------
Confusion matrix
[[69820     2     0     1   159  1588     4   127     0     0]
 [    0     3     0     0    64     1     0     0     0     0]
 [    0     0    39     0    20    32     1    12     0     0]
 [   42     0     2    39   472   277    12    71     1     0]
 [  259     1     6    24  4124  1323    20   502     0     0]
 [   89     0     0     1   365  5225     5   164     0     0]
 [   25     0     0     9   456   235   120    19     3     0]
 [   21     0     1     0   115   817     0  2435     3     0]
 [    2     0     0     1    25   272     0    79     2     0]
 [    1     0     0     0    24    19     0     2     0     0]]
----------------------------------------------------------------------
----------------------------------------------------------------------
Classification report:


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


              precision    recall  f1-score   support

           0       0.99      0.97      0.98     71701
           1       0.50      0.04      0.08        68
           2       0.81      0.38      0.51       104
           3       0.52      0.04      0.08       916
           4       0.71      0.66      0.68      6259
           5       0.53      0.89      0.67      5849
           6       0.74      0.14      0.23       867
           7       0.71      0.72      0.72      3392
           8       0.22      0.01      0.01       381
           9       0.00      0.00      0.00        46

    accuracy                           0.91     89583
   macro avg       0.57      0.38      0.40     89583
weighted avg       0.92      0.91      0.91     89583

----------------------------------------------------------------------


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
# y_pred

#**BILSTM**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = X_data.values  # Convert to NumPy array for features
y = Y_data

# Encode labels if they are categorical
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Reshape X for LSTM (samples, time steps, features)
X_reshaped = X.reshape((X.shape[0], X.shape[1], 1))  # Shape (samples, 15, 1)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_encoded, test_size=0.2, random_state=42)

# Define the Bidirectional LSTM model
model4 = models.Sequential()
model4.add(layers.Bidirectional(layers.LSTM(64, return_sequences=False), input_shape=(X_train.shape[1], 1)))
model4.add(layers.Dense(64, activation='relu'))
model4.add(layers.Dense(len(np.unique(y_encoded)), activation='softmax'))  # Use 'sigmoid' for binary classification

# Compile the model
model4.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model4.summary()

# Train the model
history = model4.fit(X_train, y_train, epochs=20, batch_size=64, validation_data=(X_test, y_test))

# Evaluate the model
test_loss, test_accuracy = model4.evaluate(X_test, y_test)
print(f'Test accuracy: {test_accuracy:.4f}')


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)        │ (None, 128)                 │          33,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 42,698 (166.79 KB)

 Trainable params: 42,698 (166.79 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 60s 10ms/step - accuracy: 0.8772 - loss: 0.3732 - val_accuracy: 0.9128 - val_loss: 0.2475
Epoch 2/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 63s 11ms/step - accuracy: 0.9123 - loss: 0.2462 - val_accuracy: 0.9169 - val_loss: 0.2307
Epoch 3/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 78s 10ms/step - accuracy: 0.9170 - loss: 0.2331 - val_accuracy: 0.9201 - val_loss: 0.2238
Epoch 4/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 80s 10ms/step - accuracy: 0.9196 - loss: 0.2258 - val_accuracy: 0.9198 - val_loss: 0.2222
Epoch 5/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 57s 10ms/step - accuracy: 0.9204 - loss: 0.2213 - val_accuracy: 0.9213 - val_loss: 0.2164
Epoch 6/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 83s 10ms/step - accuracy: 0.9222 - loss: 0.2166 - val_accuracy: 0.9223 - val_loss: 0.2136
Epoch 7/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 58s 10ms/step - accuracy: 0.9227 - loss: 0.2148 - val_accuracy: 0.9220 - val_loss: 0.2160
Epoch 8/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 81s 10ms/step - accuracy: 0.9226 -

In [ ]:
# print(test_loss,test_accuracy)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix





print("----------------------------------------------------------------------")
# print("Training Accuracy")
# display(model3.score(X_train,y_train))
# print("----------------------------------------------------------------------")

y_pred = model4.predict(X_test)
ypred= [np.argmax(x) for x in y_pred]


print("----------------------------------------------------------------------")
print("Confusion matrix")
print(confusion_matrix(y_test, ypred))
print("----------------------------------------------------------------------")

print("----------------------------------------------------------------------")
print("Classification report:")
print(classification_report(y_test, ypred))
print("----------------------------------------------------------------------")



----------------------------------------------------------------------
2800/2800 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step
----------------------------------------------------------------------
Confusion matrix
[[70112     0     0     1   215  1314     7    51     1     0]
 [    0     0     0     0    67     1     0     0     0     0]
 [    3     0    41     0    22    29     5     4     0     0]
 [   15     0     1   105   459   260    52    22     2     0]
 [   70     0     1    40  4699  1227    94   127     0     1]
 [  162     0     0     0   230  5391    11    53     2     0]
 [   12     0     0    34   156   205   454     3     3     0]
 [   63     0     0    13   392   726     0  2197     1     0]
 [    4     0     0    10    53   272     0    24    18     0]
 [    3     0     0     0    23    16     1     0     0     3]]
----------------------------------------------------------------------
----------------------------------------------------------------------
Classification report:
 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# rough work

# CNN+BiLSTM

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = X_data.values
y = Y_data

# Encode labels if they are categorical
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


X_reshaped = X.reshape((X.shape[0], X.shape[1], 1))  # Shape (samples, 15, 1)

X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_encoded, test_size=0.2, random_state=42)

model5 = models.Sequential()

model5.add(layers.Conv1D(32, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model5.add(layers.MaxPooling1D(pool_size=2))

model5.add(layers.Bidirectional(layers.LSTM(64, return_sequences=False)))
model5.add(layers.Dense(64, activation='relu'))
model5.add(layers.Dense(len(np.unique(y_encoded)), activation='softmax'))

# Compile the model
model5.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model5.summary()

history = model5.fit(X_train, y_train, epochs=20, batch_size=64, validation_data=(X_test, y_test))


test_loss, test_accuracy = model5.evaluate(X_test, y_test)
print(f'Test accuracy: {test_accuracy:.4f}')


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)                    │ (None, 74, 32)              │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_4 (MaxPooling1D)       │ (None, 37, 32)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ bidirectional_1 (Bidirectional)      │ (None, 128)                 │          49,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 58,698 (229.29 KB)

 Trainable params: 58,698 (229.29 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 53s 9ms/step - accuracy: 0.8832 - loss: 0.3385 - val_accuracy: 0.9109 - val_loss: 0.2505
Epoch 2/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 81s 9ms/step - accuracy: 0.9111 - loss: 0.2517 - val_accuracy: 0.9120 - val_loss: 0.2545
Epoch 3/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 83s 9ms/step - accuracy: 0.9110 - loss: 0.2499 - val_accuracy: 0.9135 - val_loss: 0.2364
Epoch 4/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 87s 10ms/step - accuracy: 0.9130 - loss: 0.2391 - val_accuracy: 0.9121 - val_loss: 0.2480
Epoch 5/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 79s 9ms/step - accuracy: 0.9158 - loss: 0.2331 - val_accuracy: 0.9169 - val_loss: 0.2280
Epoch 6/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 81s 9ms/step - accuracy: 0.9162 - loss: 0.2311 - val_accuracy: 0.9152 - val_loss: 0.2342
Epoch 7/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 82s 9ms/step - accuracy: 0.9161 - loss: 0.2309 - val_accuracy: 0.9174 - val_loss: 0.2271
Epoch 8/20
5599/5599 ━━━━━━━━━━━━━━━━━━━━ 83s 9ms/step - accuracy: 0.9166 - loss: 

In [ ]:
print(test_loss,test_accuracy)

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("----------------------------------------------------------------------")

y_pred = model5.predict(X_test)
ypred= [np.argmax(x) for x in y_pred]


print("----------------------------------------------------------------------")
print("Confusion matrix")
print(confusion_matrix(y_test, ypred))
print("----------------------------------------------------------------------")

print("----------------------------------------------------------------------")
print("Classification report:")
print(classification_report(y_test, ypred))
print("----------------------------------------------------------------------")



0.2154592126607895 0.9212238788604736
----------------------------------------------------------------------
2800/2800 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step
----------------------------------------------------------------------
Confusion matrix
[[69779     0     0     4   228  1629     1    54     6     0]
 [    0     0     0     0    67     1     0     0     0     0]
 [    0     0    25     7    34    33     0     5     0     0]
 [    1     0     4    61   497   280    52    19     2     0]
 [   12     0     5    11  4717  1292    68   154     0     0]
 [    2     0     0     0   304  5477     4    60     2     0]
 [    5     0     0    12   359   231   256     3     1     0]
 [    0     0     2    27   359   804     0  2198     2     0]
 [    0     0     0    20    52   279     0    17    13     0]
 [    1     0     0     0    26    19     0     0     0     0]]
----------------------------------------------------------------------
----------------------------------------------------------

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# Our Actual code BiLSTM+Random forest

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Dense, Input, GlobalAveragePooling1D

# Load the encoded dataset (replace with the actual file path)
# data = pd.read_csv('encoded_intrusion_data.csv')

# Assume the target column is 'label'
# X = X_data  # Feature columns
# y = y               # Target column

# # Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_data,Y_data, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Reshape for LSTM input: [samples, timesteps, features]
X_train_reshaped = X_train_scaled.reshape(X_train_scaled.shape[0], 1, X_train_scaled.shape[1])
X_test_reshaped = X_test_scaled.reshape(X_test_scaled.shape[0], 1, X_test_scaled.shape[1])

# BiLSTM Model for Feature Extraction
embedding_dim = 64

bilstm_model = Sequential([
    Input(shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2])),
    Bidirectional(LSTM(64, return_sequences=True)),
    GlobalAveragePooling1D(),
    Dense(32, activation='relu')
])

X_train_embeddings = bilstm_model.predict(X_train_reshaped)
X_test_embeddings = bilstm_model.predict(X_test_reshaped)

rf_model = RandomForestClassifier(n_estimators=500, random_state=42)
rf_model.fit(X_train_embeddings, y_train)

y_pred = rf_model.predict(X_test_embeddings)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


11198/11198 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step
2800/2800 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Accuracy: 0.9272964736612973

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99     71701
           1       0.32      0.22      0.26        68
           2       0.74      0.38      0.51       104
           3       0.53      0.24      0.33       916
           4       0.72      0.78      0.75      6259
           5       0.64      0.77      0.70      5849
           6       0.78      0.63      0.70       867
           7       0.72      0.68      0.70      3392
           8       0.42      0.27      0.33       381
           9       0.21      0.07      0.10        46

    accuracy                           0.93     89583
   macro avg       0.61      0.50      0.54     89583
weighted avg       0.93      0.93      0.93     89583



In [ ]:
rf_model.score(X_train_embeddings,y_train)

0.9973878972572922

In [ ]:

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print("----------------------------------------------------------------------")
y_pred = rf_model.predict(X_test_embeddings)


print("----------------------------------------------------------------------")
print("Confusion matrix")
print(confusion_matrix(y_test, y_pred))
print("----------------------------------------------------------------------")

print("----------------------------------------------------------------------")
print("Classification report:")
print(classification_report(y_test, y_pred))
print("----------------------------------------------------------------------")



----------------------------------------------------------------------
----------------------------------------------------------------------
Confusion matrix
[[70450     7     0    16   237   826    23   128    12     2]
 [   14    15     0     6    32     1     0     0     0     0]
 [    3     0    40     1    24    26     1     9     0     0]
 [   35     7     5   220   385   181    18    52    12     1]
 [  127    16     3    87  4861   757    50   330    23     5]
 [  305     2     3    46   509  4515    58   335    74     2]
 [   22     0     1     4   162   102   549    19     8     0]
 [   92     0     1    24   421   518     6  2315    14     1]
 [   21     0     1     9    59   152     2    35   102     0]
 [    4     0     0     0    19    16     1     3     0     3]]
----------------------------------------------------------------------
----------------------------------------------------------------------
Classification report:
              precision    recall  f1-score  

In [ ]:
typesOfAttack={
    0: "Benign",
    1: "Analysis",
    2: "Backdoor",
    3: "DoS",
    4: "Exploits",
    5: "Fuzzers",
    6: "Generic",
    7: "Reconnaissance",
    8: "Shellcode",
    9: "Worms"
}


In [ ]:
def predict_intrusion(new_tuple, scaler, bilstm_model, rf_model, label_encoder=None):
        new_tuple_scaled = scaler.transform(new_tuple.reshape(1, -1))

        new_tuple_reshaped = new_tuple_scaled.reshape(1, 1, new_tuple_scaled.shape[1])

        new_tuple_embedding = bilstm_model.predict(new_tuple_reshaped)

        new_prediction = rf_model.predict(new_tuple_embedding)
        print(new_prediction)

        return new_prediction


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)


prediction = predict_intrusion(X_data.iloc[1].values, scaler, bilstm_model, rf_model)
typeOfAttacks = {
    0: "Benign",
    1: "Analysis",
    2: "Backdoor",
    3: "DoS",
    4: "Exploits",
    5: "Fuzzers",
    6: "Generic",
    7: "Reconnaissance",
    8: "Shellcode",
    9: "Worms"
}


if prediction in listOfIntrusionTypes:
    print("Intrusion atack")
    print(f"Prediction: {prediction[0]}")

else:
    print("Not a intrusion atack")
    print(f"Prediction: {prediction[0]}")



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[7]
Intrusion atack
Prediction: 7


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
Y_data.iloc[1]


Label    7
Name: 1, dtype: int64

In [ ]:
X_test.shape

(89583, 76, 1)